Frontend rebuild
Gamify-IT/regexgame pull request #18
Opened 2023-03-02 16:11 UTC by programminghoch10

This is a complete visual reimplementation of the title screen and one question.
This includes animations and user feedback whether their selected answer was correct or not.

Closes Gamify-IT/issues#465

2023-03-02 16:15 UTC, programminghoch10 commented
@madebyTimo please review the changed dockerfile

2023-03-02 16:25 UTC, robojones approved these changes

2023-03-03 12:05 UTC, madebyTimo requested changes

2023-03-03 13:55 UTC, programminghoch10 commented on package.json
> +  "devDependencies": {
formatting is covered by vscode internal formatter, which has now been explicitely configured with similar rules to prettier
linting is included in vscode, and also in sonarcube (ish, main only)

2023-03-03 14:15 UTC, delvh approved these changes

2023-03-07 21:51 UTC, madebyTimo approved these changes

2023-03-08 16:53 UTC, merged